language: python

python:
  - '2.7'
  - '3.3'

env:
  global:
    - DJANGO_SECRET_KEY=my-secret-key-for-testing
  matrix:
    - DJANGO="django==1.6.5"
    - DJANGO="django==1.5.8"
    - DJANGO="django==1.4.13"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test --configuration=Testing --verbosity=3 --noinput

notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: oHinMi1k33ZF/oSXF3o0Whi8rOohcvj+SkiFEgOrmlSR1wQBhlg03ETgZtKPaI000EVxMwBQCzXMweqO7F49Z2ofm/DTPD2aPRG/BAUetg67b/VmZkYhoDpUBV2ovdWa4jSAOd73kkstWqZRU5cQh5RV1OsLBXda/MubrIS1p90=
    on_success: change
    on_failure: change
