language: python

python:
  - "2.7"
  - "3.3"

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - DJANGO="django==1.6"
  - DJANGO="django==1.5.5"
  - DJANGO="django==1.4.10"
  - DJANGO="django==1.3.7"

install:
  - pip install tox

script:
  - tox -e $TOX_ENV